edition = "2021"
max_width = 100
use_field_init_shorthand = true
use_try_shorthand = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true
newline_style = "Unix"
tab_spaces = 4
hard_tabs = false
trailing_comma = "Vertical"
trailing_semicolon = true
format_strings = false
