//! Profit calculator with Arbitrum 2D gas model (L2 execution + L1 calldata).
//!
//! # Why two-dimensional gas matters
//! On Arbitrum every transaction pays two costs:
//! 1. **L2 execution gas** — what `eth_estimateGas` returns.
//! 2. **L1 calldata gas** — cost of posting the tx back to Ethereum mainnet.
//!
//! During mainnet congestion the L1 component can reach $1.50+, silently
//! turning a profitable simulation into an on-chain loss.  The
//! [`GasFetcher::estimate_l1_gas`] method calls the Arbitrum NodeInterface
//! precompile at `0x…C8` via `gasEstimateL1Component` to get the real cost.
//!
//! # Design for testability
//! All RPC calls are routed through the [`GasFetcher`] trait.  Tests inject
//! `MockGasFetcher` (generated by mockall) and never touch the network.

use std::sync::{Arc, RwLock};

use alloy::network::Ethereum;
use alloy::primitives::{Address, Bytes, U256};
use alloy::providers::RootProvider;
use anyhow::Context as _;
use arbx_common::config::StrategyConfig;
use arbx_common::types::{ArbPath, GasEstimate, Opportunity};
use tracing::debug;

// ─── GasFetcher trait ────────────────────────────────────────────────────────

/// Abstraction over all RPC calls made by the profit calculator.
///
/// `#[cfg_attr(test, mockall::automock)]` generates `MockGasFetcher` in test
/// builds so that every test runs without a live Arbitrum node.
///
/// `eth_price_usd` is intentionally **non-async**: it returns a cached value
/// updated by a background task, so no network round-trip is needed on the
/// hot path.
#[cfg_attr(test, mockall::automock)]
#[async_trait::async_trait]
pub trait GasFetcher: Send + Sync {
    /// Current L2 execution gas price in wei.
    async fn l2_gas_price_wei(&self) -> anyhow::Result<u128>;

    /// Estimates L2 execution gas units for the given call.
    async fn estimate_l2_gas(&self, to: Address, data: Bytes) -> anyhow::Result<u64>;

    /// Estimates L1 calldata gas units via Arbitrum's NodeInterface precompile
    /// (`0x00…C8`, function `gasEstimateL1Component`).
    async fn estimate_l1_gas(&self, to: Address, data: Bytes) -> anyhow::Result<u64>;

    /// L1 base fee in wei (from NodeInterface `l1BaseFeeEstimate`).
    async fn l1_base_fee_wei(&self) -> anyhow::Result<u128>;

    /// Cached ETH/USD spot price — synchronous, updated by a background task.
    fn eth_price_usd(&self) -> f64;
}

// ─── AlloyGasFetcher ─────────────────────────────────────────────────────────

/// Production [`GasFetcher`] backed by an alloy [`RootProvider<Ethereum>`].
///
/// Uses Arbitrum's NodeInterface precompile at address
/// `0x00000000000000000000000000000000000000C8` for the L1 cost component.
pub struct AlloyGasFetcher {
    provider: Arc<RootProvider<Ethereum>>,
    /// Arbitrum NodeInterface precompile (`0x00…C8`).
    node_interface: Address,
    /// Periodically refreshed by a background price-feed task.
    eth_price_usd: Arc<RwLock<f64>>,
}

impl AlloyGasFetcher {
    /// Constructs a new fetcher.
    ///
    /// `eth_price_usd` must be refreshed externally (e.g. via a CoinGecko
    /// price-feed task) — the calculator reads it on every profitability check.
    pub fn new(
        provider: Arc<RootProvider<Ethereum>>,
        node_interface: Address,
        eth_price_usd: Arc<RwLock<f64>>,
    ) -> Self {
        Self {
            provider,
            node_interface,
            eth_price_usd,
        }
    }
}

#[async_trait::async_trait]
impl GasFetcher for AlloyGasFetcher {
    async fn l2_gas_price_wei(&self) -> anyhow::Result<u128> {
        use alloy::providers::Provider as _;
        Ok(self.provider.get_gas_price().await?)
    }

    async fn estimate_l2_gas(&self, _to: Address, _data: Bytes) -> anyhow::Result<u64> {
        // TODO: provider.estimate_gas(TransactionRequest { to, input: data, .. })
        anyhow::bail!("AlloyGasFetcher::estimate_l2_gas not yet implemented")
    }

    async fn estimate_l1_gas(&self, _to: Address, _data: Bytes) -> anyhow::Result<u64> {
        // TODO: INodeInterface::new(self.node_interface, &*self.provider)
        //       .gasEstimateL1Component(to, false, data).call().await
        let _ = self.node_interface; // suppress unused warning
        anyhow::bail!("AlloyGasFetcher::estimate_l1_gas not yet implemented")
    }

    async fn l1_base_fee_wei(&self) -> anyhow::Result<u128> {
        // TODO: derive from NodeInterface.gasEstimateL1Component.l1BaseFeeEstimate
        anyhow::bail!("AlloyGasFetcher::l1_base_fee_wei not yet implemented")
    }

    fn eth_price_usd(&self) -> f64 {
        *self
            .eth_price_usd
            .read()
            .expect("eth_price_usd RwLock poisoned")
    }
}

// ─── Pure computation helper ─────────────────────────────────────────────────

/// Pure (no I/O) minimum-profit computation — exported for property tests.
///
/// ```text
/// min_profit = total_gas_cost × gas_buffer_multiplier
///            + (min_profit_floor_usd / eth_price_usd) × 10^18
/// ```
///
/// Integer scaling (`× 1_000_000_000 / 1_000_000_000`) is used for the buffer
/// multiply to avoid f64 precision drift on large U256 values.
pub fn compute_min_profit_pure(
    total_cost_wei: U256,
    gas_buffer_multiplier: f64,
    min_profit_floor_usd: f64,
    eth_price_usd: f64,
) -> U256 {
    // Scale the multiplier into an integer to stay in U256 arithmetic.
    // E.g.  1.1  → 1_100_000_000  → divide by 1_000_000_000 at the end.
    let buffer_num = (gas_buffer_multiplier * 1_000_000_000.0) as u128;
    let buffered_gas = (total_cost_wei * U256::from(buffer_num)) / U256::from(1_000_000_000u128);

    let floor_wei = if eth_price_usd > 0.0 {
        U256::from((min_profit_floor_usd / eth_price_usd * 1e18) as u128)
    } else {
        U256::ZERO
    };

    buffered_gas + floor_wei
}

// ─── ProfitCalculator ────────────────────────────────────────────────────────

/// Evaluates candidate arb paths against the Arbitrum 2D-gas dynamic threshold.
///
/// The threshold adapts automatically to mainnet gas spikes: during quiet
/// periods the floor dominates; during congestion the L1 calldata cost
/// dominates, raising the bar so the bot never submits losing transactions.
pub struct ProfitCalculator<G: GasFetcher> {
    fetcher: G,
    strategy: StrategyConfig,
}

impl<G: GasFetcher> ProfitCalculator<G> {
    /// Constructs a new calculator.
    pub fn new(fetcher: G, strategy: StrategyConfig) -> Self {
        Self { fetcher, strategy }
    }

    /// Fetches both L2 execution gas and L1 calldata gas, assembles a full
    /// [`GasEstimate`] with both cost components and the USD equivalent.
    pub async fn estimate_gas(&self, to: Address, calldata: Bytes) -> anyhow::Result<GasEstimate> {
        let l2_gas_units = self
            .fetcher
            .estimate_l2_gas(to, calldata.clone())
            .await
            .context("estimate_l2_gas failed")?;
        let l2_price = self
            .fetcher
            .l2_gas_price_wei()
            .await
            .context("l2_gas_price_wei failed")?;
        let l1_gas_units = self
            .fetcher
            .estimate_l1_gas(to, calldata)
            .await
            .context("estimate_l1_gas failed")?;
        let l1_base = self
            .fetcher
            .l1_base_fee_wei()
            .await
            .context("l1_base_fee_wei failed")?;
        let eth_price = self.fetcher.eth_price_usd();

        let l2_cost = U256::from(l2_gas_units as u128 * l2_price);
        let l1_cost = U256::from(l1_gas_units as u128 * l1_base);
        let total_cost = l2_cost + l1_cost;

        // total_cost_usd is informational (used for observability logging).
        let total_cost_usd = if eth_price > 0.0 {
            let wei_f64 =
                (l2_gas_units as f64 * l2_price as f64) + (l1_gas_units as f64 * l1_base as f64);
            wei_f64 / 1e18 * eth_price
        } else {
            0.0
        };

        Ok(GasEstimate {
            l2_gas_units,
            l2_gas_price_wei: l2_price,
            l2_cost_wei: l2_cost,
            l1_calldata_gas: l1_gas_units,
            l1_base_fee_wei: l1_base,
            l1_cost_wei: l1_cost,
            total_cost_wei: total_cost,
            total_cost_usd,
        })
    }

    /// Computes the minimum acceptable profit in wei for a given gas estimate.
    ///
    /// Delegates to [`compute_min_profit_pure`] with the cached ETH price and
    /// current strategy parameters.
    pub fn compute_min_profit_wei(&self, gas: &GasEstimate) -> U256 {
        compute_min_profit_pure(
            gas.total_cost_wei,
            self.strategy.gas_buffer_multiplier,
            self.strategy.min_profit_floor_usd,
            self.fetcher.eth_price_usd(),
        )
    }

    /// Returns `Some(Opportunity)` only when `path.estimated_profit_wei` is
    /// **strictly greater** than `compute_min_profit_wei`.
    ///
    /// Gas is estimated against `path.pool_a` — the first contract the
    /// on-chain transaction touches.
    pub async fn filter(
        &self,
        path: &ArbPath,
        calldata: Bytes,
    ) -> anyhow::Result<Option<Opportunity>> {
        let gas = self
            .estimate_gas(path.pool_a, calldata)
            .await
            .context("gas estimation failed in filter")?;

        let min_profit = self.compute_min_profit_wei(&gas);

        if path.estimated_profit_wei <= min_profit {
            debug!(
                pool_a  = %path.pool_a,
                profit  = %path.estimated_profit_wei,
                min     = %min_profit,
                "path below profit threshold — skipping"
            );
            return Ok(None);
        }

        let net_profit_wei = path.estimated_profit_wei.saturating_sub(gas.total_cost_wei);
        let detected_at_ms = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis() as u64;

        Ok(Some(Opportunity {
            path: path.clone(),
            gross_profit_wei: path.estimated_profit_wei,
            l2_gas_cost_wei: gas.l2_cost_wei,
            l1_gas_cost_wei: gas.l1_cost_wei,
            net_profit_wei,
            detected_at_ms,
        }))
    }
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use alloy::primitives::Address;
    use arbx_common::types::GasEstimate;

    // ── Helpers ──────────────────────────────────────────────────────────────

    fn addr(seed: u8) -> Address {
        Address::from([seed; 20])
    }

    fn make_strategy() -> StrategyConfig {
        StrategyConfig {
            min_profit_floor_usd: 0.50,
            gas_buffer_multiplier: 1.1,
            max_gas_gwei: 0.1,
            flash_loan_fee_bps: 0,
        }
    }

    /// Construct a GasEstimate with specific numeric components.
    fn make_gas_estimate(
        l2_gas: u64,
        l2_price: u128,
        l1_gas: u64,
        l1_base: u128,
        eth_price: f64,
    ) -> GasEstimate {
        let l2_cost = U256::from(l2_gas as u128 * l2_price);
        let l1_cost = U256::from(l1_gas as u128 * l1_base);
        let total = l2_cost + l1_cost;
        let total_usd = if eth_price > 0.0 {
            (l2_gas as f64 * l2_price as f64 + l1_gas as f64 * l1_base as f64) / 1e18 * eth_price
        } else {
            0.0
        };
        GasEstimate {
            l2_gas_units: l2_gas,
            l2_gas_price_wei: l2_price,
            l2_cost_wei: l2_cost,
            l1_calldata_gas: l1_gas,
            l1_base_fee_wei: l1_base,
            l1_cost_wei: l1_cost,
            total_cost_wei: total,
            total_cost_usd: total_usd,
        }
    }

    /// Construct a GasEstimate with only total_cost_wei set (others zeroed).
    fn gas_with_total(total: U256) -> GasEstimate {
        GasEstimate {
            l2_gas_units: 0,
            l2_gas_price_wei: 0,
            l2_cost_wei: U256::ZERO,
            l1_calldata_gas: 0,
            l1_base_fee_wei: 0,
            l1_cost_wei: U256::ZERO,
            total_cost_wei: total,
            total_cost_usd: 0.0,
        }
    }

    /// Build a mock with all five methods returning known constants.
    fn make_mock(
        l2_gas: u64,
        l2_price: u128,
        l1_gas: u64,
        l1_base: u128,
        eth_price: f64,
    ) -> MockGasFetcher {
        let mut mock = MockGasFetcher::new();
        mock.expect_estimate_l2_gas()
            .returning(move |_, _| Ok(l2_gas));
        mock.expect_l2_gas_price_wei()
            .returning(move || Ok(l2_price));
        mock.expect_estimate_l1_gas()
            .returning(move |_, _| Ok(l1_gas));
        mock.expect_l1_base_fee_wei().returning(move || Ok(l1_base));
        mock.expect_eth_price_usd().returning(move || eth_price);
        mock
    }

    /// Minimal ArbPath for filter tests.
    fn make_path(estimated_profit_wei: U256) -> ArbPath {
        ArbPath {
            token_in: addr(1),
            pool_a: addr(10),
            token_mid: addr(2),
            pool_b: addr(11),
            token_out: addr(1),
            estimated_profit_wei,
            flash_loan_amount_wei: U256::from(1_000_000u64),
        }
    }

    // ── Unit tests ────────────────────────────────────────────────────────────

    /// estimate_gas correctly sums L2 and L1 components.
    ///
    /// l2_cost = 200_000 × 100 gwei  = 20_000_000_000_000_000 wei
    /// l1_cost =   5_000 ×  20 gwei  =        100_000_000_000_000 wei
    /// total                         = 20_100_000_000_000_000 wei
    #[tokio::test]
    async fn test_gas_estimate_sums_l2_and_l1() {
        const L2_GAS: u64 = 200_000;
        const L2_PRICE: u128 = 100_000_000_000; // 100 gwei
        const L1_GAS: u64 = 5_000;
        const L1_BASE: u128 = 20_000_000_000; // 20 gwei

        let mock = make_mock(L2_GAS, L2_PRICE, L1_GAS, L1_BASE, 2000.0);
        let calc = ProfitCalculator::new(mock, make_strategy());

        let gas = calc.estimate_gas(addr(10), Bytes::new()).await.unwrap();

        let expected_l2 = U256::from(L2_GAS as u128 * L2_PRICE); // 20_000_000_000_000_000
        let expected_l1 = U256::from(L1_GAS as u128 * L1_BASE); //        100_000_000_000_000
        let expected_total = expected_l2 + expected_l1; //         20_100_000_000_000_000

        assert_eq!(gas.l2_cost_wei, expected_l2, "L2 cost mismatch");
        assert_eq!(gas.l1_cost_wei, expected_l1, "L1 cost mismatch");
        assert_eq!(gas.total_cost_wei, expected_total, "total cost mismatch");
    }

    /// compute_min_profit_wei includes both the buffer and the USD floor.
    ///
    /// floor_in_wei = 0.50 / 3000 × 1e18 ≈ 166_666_666_666_666 wei
    /// gas_cost     = 1_000_000_000_000_000 wei
    /// buffered     = gas_cost × 1.1       = 1_100_000_000_000_000 wei
    /// expected_min = buffered + floor      ≈ 1_266_666_666_666_666 wei
    #[test]
    fn test_min_profit_includes_floor() {
        let mut mock = MockGasFetcher::new();
        mock.expect_eth_price_usd().returning(|| 3000.0);

        let calc = ProfitCalculator::new(mock, make_strategy());
        let gas = gas_with_total(U256::from(1_000_000_000_000_000u64));
        let min = calc.compute_min_profit_wei(&gas);

        let expected = U256::from(1_266_666_666_666_666u128);
        // Allow ≤1 wei tolerance for f64 truncation of the floor term.
        let diff = if min >= expected {
            min - expected
        } else {
            expected - min
        };
        assert!(
            diff <= U256::from(1u64),
            "expected ≈{expected}, got {min} (diff={diff})"
        );
    }

    /// A path whose profit is 2× the minimum threshold passes the filter.
    #[tokio::test]
    async fn test_profitable_path_passes_filter() {
        const L2_GAS: u64 = 200_000;
        const L2_PRICE: u128 = 100_000_000_000;
        const L1_GAS: u64 = 5_000;
        const L1_BASE: u128 = 20_000_000_000;
        const ETH_PRICE: f64 = 2000.0;

        // Compute min_profit directly (pure, no mock) to set the path profit.
        let total = U256::from(L2_GAS as u128 * L2_PRICE + L1_GAS as u128 * L1_BASE);
        let min_profit = compute_min_profit_pure(total, 1.1, 0.50, ETH_PRICE);

        // filter() needs a mock that returns all gas values.
        let mock = make_mock(L2_GAS, L2_PRICE, L1_GAS, L1_BASE, ETH_PRICE);
        let calc = ProfitCalculator::new(mock, make_strategy());
        let path = make_path(min_profit * U256::from(2u32));

        let result = calc.filter(&path, Bytes::new()).await.unwrap();
        assert!(result.is_some(), "2× min_profit should pass the filter");
    }

    /// A path whose profit is half the minimum threshold is rejected.
    #[tokio::test]
    async fn test_unprofitable_path_filtered() {
        const L2_GAS: u64 = 200_000;
        const L2_PRICE: u128 = 100_000_000_000;
        const L1_GAS: u64 = 5_000;
        const L1_BASE: u128 = 20_000_000_000;
        const ETH_PRICE: f64 = 2000.0;

        let total = U256::from(L2_GAS as u128 * L2_PRICE + L1_GAS as u128 * L1_BASE);
        let min_profit = compute_min_profit_pure(total, 1.1, 0.50, ETH_PRICE);

        let mock = make_mock(L2_GAS, L2_PRICE, L1_GAS, L1_BASE, ETH_PRICE);
        let calc = ProfitCalculator::new(mock, make_strategy());
        let path = make_path(min_profit / U256::from(2u32));

        let result = calc.filter(&path, Bytes::new()).await.unwrap();
        assert!(result.is_none(), "½× min_profit should be filtered out");
    }

    /// L1 gas spike (1000× baseline) raises the threshold by more than 100×.
    ///
    /// Uses an astronomical ETH price so the USD floor term (`$0.50 / ETH_PRICE`)
    /// becomes negligible in wei, letting us measure the pure L1-cost ratio
    /// without the constant floor overwhelming the baseline.
    #[test]
    fn test_gas_spike_raises_threshold() {
        // $10 M / ETH → floor_wei ≈ 5e10 wei — negligible vs gas costs.
        const ETH_PRICE: f64 = 10_000_000.0;

        // baseline: 1_000 L1 units × 5 gwei = 5_000_000_000_000 wei
        let baseline_total = U256::from(1_000u128 * 5_000_000_000u128);
        let threshold_baseline = compute_min_profit_pure(baseline_total, 1.1, 0.50, ETH_PRICE);

        // spike: 100_000 L1 units × 50 gwei = 5_000_000_000_000_000 wei (1_000× more)
        let spike_total = U256::from(100_000u128 * 50_000_000_000u128);
        let threshold_spike = compute_min_profit_pure(spike_total, 1.1, 0.50, ETH_PRICE);

        assert!(
            threshold_spike > threshold_baseline * U256::from(100u32),
            "gas spike (1000×) should raise threshold >100×: \
             baseline={threshold_baseline}, spike={threshold_spike}"
        );
    }

    /// Zero-profit path is always filtered out.
    #[tokio::test]
    async fn test_zero_profit_path_filtered() {
        let mock = make_mock(200_000, 100_000_000_000, 5_000, 20_000_000_000, 2000.0);
        let calc = ProfitCalculator::new(mock, make_strategy());
        let path = make_path(U256::ZERO);

        let result = calc.filter(&path, Bytes::new()).await.unwrap();
        assert!(result.is_none(), "zero-profit path must be filtered");
    }

    /// Exact-at-threshold ⟹ None; one-wei-above ⟹ Some.
    #[tokio::test]
    async fn test_exact_threshold_boundary() {
        const L2_GAS: u64 = 200_000;
        const L2_PRICE: u128 = 100_000_000_000;
        const L1_GAS: u64 = 5_000;
        const L1_BASE: u128 = 20_000_000_000;
        const ETH_PRICE: f64 = 2000.0;

        let total = U256::from(L2_GAS as u128 * L2_PRICE + L1_GAS as u128 * L1_BASE);
        let min_profit = compute_min_profit_pure(total, 1.1, 0.50, ETH_PRICE);

        // === profit == min_profit → None ===
        let mock1 = make_mock(L2_GAS, L2_PRICE, L1_GAS, L1_BASE, ETH_PRICE);
        let calc1 = ProfitCalculator::new(mock1, make_strategy());
        let result_exact = calc1
            .filter(&make_path(min_profit), Bytes::new())
            .await
            .unwrap();
        assert!(
            result_exact.is_none(),
            "profit == min_profit must return None (not strictly profitable)"
        );

        // === profit == min_profit + 1 → Some ===
        let mock2 = make_mock(L2_GAS, L2_PRICE, L1_GAS, L1_BASE, ETH_PRICE);
        let calc2 = ProfitCalculator::new(mock2, make_strategy());
        let result_above = calc2
            .filter(&make_path(min_profit + U256::from(1u32)), Bytes::new())
            .await
            .unwrap();
        assert!(
            result_above.is_some(),
            "profit == min_profit + 1 must return Some"
        );
    }

    // ── Property tests ────────────────────────────────────────────────────────

    mod property_tests {
        use super::*;
        use proptest::prelude::*;

        proptest! {
            /// Any valid gas estimate always produces a strictly positive minimum profit
            /// (gas buffer × cost + floor is always > 0).
            #[test]
            fn prop_threshold_always_positive(
                total_gas_wei in 0u128..100_000_000_000_000_000u128,  // up to ~0.1 ETH
                eth_price     in 100.0f64..20_000.0f64,
            ) {
                let min = compute_min_profit_pure(
                    U256::from(total_gas_wei),
                    1.1,
                    0.50,
                    eth_price,
                );
                // min_profit must be strictly positive:
                // even if gas_cost=0, the floor term (0.50 USD / eth_price * 1e18) > 0.
                prop_assert!(min > U256::ZERO, "threshold must always be positive, got {min}");
            }

            /// Strictly monotone: higher total gas cost ⟹ higher threshold.
            ///
            /// The threshold is linear in `total_cost_wei` (buffer term dominates
            /// for large gas; floor is constant), so any increase in gas must
            /// raise the threshold.
            #[test]
            fn prop_higher_gas_higher_threshold(
                gas_a in 1u128..50_000_000_000_000_000u128,
                gas_b in 1u128..50_000_000_000_000_000u128,
            ) {
                // Ensure a < b.
                let (lo, hi) = if gas_a <= gas_b { (gas_a, gas_b) } else { (gas_b, gas_a) };
                if lo == hi {
                    return Ok(()); // skip degenerate case
                }

                let threshold_lo =
                    compute_min_profit_pure(U256::from(lo), 1.1, 0.50, 3000.0);
                let threshold_hi =
                    compute_min_profit_pure(U256::from(hi), 1.1, 0.50, 3000.0);

                prop_assert!(
                    threshold_hi > threshold_lo,
                    "higher gas must yield higher threshold: lo={lo}, hi={hi}, \
                     threshold_lo={threshold_lo}, threshold_hi={threshold_hi}"
                );
            }
        }
    }
}
